version: "3.7"

services:
  Domain-Unchained:
    container_name: Domain-Unchained
    image: balazsmanus/domain:latest
    ports:
      - 4500:4500
    volumes:
      # you may want to change the configuration
      - ./config.json:/app/config.json:ro
      # this should stay modifiable
      - ./data:/app/data/running
      # path to u r prompts
      - ./prompts:/app/prompts:ro
    restart: unless-stopped